benchmarks_description:

- code: "STB"
  desc: "Test Benchmark: Simple Test Benchmark"
  scripted: true
  multiple_robots: false
  commands_devices: false
  order: -100
  default_goal_timeout: 30.0
  global_timeout: 120.0
  scoring:
    - Penalized Behaviors:
      - { type: uint, desc: "The robot bumps into the furniture or people." }
    - Disqualifying Behaviors:
      - { type: uint, desc: "The robot hits people or the furniture." }
      - { type: uint, desc: "The robot damages the test bed." }
  record_topics:
    - "actor_markerset/pose"
    - "actor_markerset/pose2d"

- code: "HGTKMH"
  desc: "Task Benchmark 1: Getting to know my home"
  scripted: false
  multiple_robots: false
  commands_devices: false
  order: 2
  timeout: 600.0
  scoring:
    - Achievements:
      - { type: bool, desc: "The robot detects the door with changed state." }
      - { type: uint, desc: "The robot detects each piece of moved furniture." }
      - { type: uint, desc: "The robot detects each changed object." }
      - { type: bool, desc: "The robot correctly executes the command given in Phase 2." }
    - Penalized Behaviors:
      - { type: uint, desc: "The robot requires multiple repetitions of human gesture/speech." }
      - { type: uint, desc: "The robot bumps into the furniture." }
      - { type: uint, desc: "The robot stops working." }
    - Disqualifying Behaviors:
      - { type: uint, desc: "The robot hits Annie or another person in the environment." }
      - { type: uint, desc: "The robot damages the test bed." }

- code: "HWV"
  desc: "Task Benchmark 2: Welcoming visitors"
  scripted: false
  multiple_robots: false
  commands_devices: false
  order: 3
  timeout: 600.0
  scoring:
    - Achievements:
      - { type: bool, desc: "The robot reaches the door when the door bell is rung by Dr. Kimble and correctly identifies him." }
      - { type: bool, desc: "The robot reaches the door when the door bell is rung by the Deli Man and correctly identifies him." }
      - { type: bool, desc: "The robot reaches the door when the door bell is rung by the PostMan and correctly identifies him." }
      - { type: bool, desc: "The robot reaches the door when the door bell is rung by an unknown person and correctly identifies the person as such." }
      - { type: bool, desc: "The robot exhibits the expected behavior for interacting with Dr. Kimble." }
      - { type: bool, desc: "The robot exhibits the expected behavior for interacting with the Deli Man." }
      - { type: bool, desc: "The robot exhibits the expected behavior for interacting with the PostMan." }
      - { type: bool, desc: "The robot exhibits the expected behavior for interacting with an unknown person." }
    - Penalized Behaviors:
      - { type: uint, desc: "The robot fails in making the visitor respect the proper rights." }
      - { type: uint, desc: "The robot generates false alarms." }
      - { type: uint, desc: "The robot fails in maintaining the original state of the environment." }
      - { type: uint, desc: "The robot requires extra repetitions of speech." }
      - { type: uint, desc: "The robot bumps into the furniture." }
      - { type: uint, desc: "The robot stops working." }
    - Disqualifying Behaviors:
      - { type: uint, desc: "The robot hits Annie or one of the visitors." }
      - { type: uint, desc: "The robot damages the test bed. " }

- code: "HCFGAC"
  desc: "Task Benchmark 3: Catering for Granny Annie's Comfort"
  scripted: false
  multiple_robots: false
  commands_devices: true
  order: 4
  timeout: 600.0
  scoring:
    - Achievements:
      - { type: bool, desc: "The robot enters the room where Granny Annie is waiting." }
      - { type: bool, desc: "The robot understands Annieâ€™s command(s)." }
      - { type: uint, desc: "The robot operates correctly the right device(s)." }
      - { type: uint, desc: "The robot finds the right object(s)." }
      - { type: uint, desc: "The robot brings to Annie the right object(s)." }
    - Penalized Behaviors:
      - { type: uint, desc: "The robot bumps into the furniture." }
      - { type: uint, desc: "The robot drops an object." }
      - { type: uint, desc: "The robot stops working." }
    - Disqualifying Behaviors:
      - { type: uint, desc: "The robot hits Annie or another person in the environment." }
      - { type: uint, desc: "The robot damages or destroys the objects requested to manipulate." }
      - { type: uint, desc: "The robot damages the test bed." }

- code: "HOPF"
  desc: "Functionality Benchmark 1: Object Perception Functionality"
  scripted: true
  multiple_robots: false
  commands_devices: false
  order: -3
  default_goal_timeout: 120.0
  global_timeout: 600.0
  record_topics:
    - "table_origin/pose"
    - "table_origin/pose2d"
    - "positioner_origin/pose"
    - "positioner_origin/pose2d"

- code: "HNF"
  desc: "Functionality Benchmark 2: Navigation Functionality"
  scripted: true
  multiple_robots: false
  commands_devices: false
  order: -2
  default_goal_timeout: 120.0
  global_timeout: 600.0
  scoring:
    - Penalized Behaviors:
      - { type: uint, desc: "The robot bumps into the furniture or people." }
    - Disqualifying Behaviors:
      - { type: uint, desc: "The robot hits people or the furniture." }
      - { type: uint, desc: "The robot damages the test bed." }
  record_topics:
    - "robot_markerset/pose"
    - "robot_markerset/pose2d"
    - "actor_markerset/pose"
    - "actor_markerset/pose2d"

- code: "HSUF"
  desc: "Functionality Benchmark 3: Speech Understanding Functionality"
  scripted: false
  multiple_robots: true
  commands_devices: false
  order: 7
  timeout: 120.0



